server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /redcode
  port: 8093
  compression:
    enabled: true
  http2:
    enabled: true

spring:
  profiles:
    active: dev
  aop:
    proxy-target-class: true
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  application:
    name: redweb
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  datasource:
    druid:
        connection-init-sqls: set names utf8mb4
        driver-class-name: com.mysql.jdbc.Driver
        test-on-borrow: true
        test-while-idle: true
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${DATASOURCE_HOST:127.0.0.1}:${DATASOURCE_PORT:3306}/${DATASOURCE_DATABASE_NAME:dblog}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root123}
    ####### Redis Config #######
  redis:
      # Redis服务器地址
    host: ${REDIS_HOST:127.0.0.1}
      # Redis服务器连接端口
    port: ${REDIS_PORT:6379}
      # Redis服务器连接密码（默认为空）
    #password: ${REDIS_PASSWORD:123456ZHYD}
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
    configuration:
      #自动下划线驼峰转换
      map-underscore-to-camel-case: true
      #打开二级缓存
      #    cache-enabled: true
      #懒加载
      lazy-loading-enabled: true
      #输出sql执行语句和结果到控制台
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 1
      #主键生成策略
      #      id-type: AUTO
      # Sequence序列接口实现类配置
      #      key-generator: com.baomidou.mybatisplus.extension.incrementer.OracleKeyGenerator
      db-config:
        logic-delete-value: "Y" # 逻辑已删除值(默认为 Y)
        logic-not-delete-value: "N" # 逻辑未删除值(默认为 N)
    mapper-locations: classpath*:mapper/**/*.xml